set -e
true
true
/Users/fionashavilof/miniconda3/envs/genomeanalysis/bin/spades-hammer /Users/fionashavilof/Desktop/GAASR/spadesoutput/corrected/configs/config.info
/Users/fionashavilof/miniconda3/envs/genomeanalysis/bin/python3 /Users/fionashavilof/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/compress_all.py --input_file /Users/fionashavilof/Desktop/GAASR/spadesoutput/corrected/corrected.yaml --ext_python_modules_home /Users/fionashavilof/miniconda3/envs/genomeanalysis/share/spades --max_threads 16 --output_dir /Users/fionashavilof/Desktop/GAASR/spadesoutput/corrected --gzip_output
true
true
/Users/fionashavilof/miniconda3/envs/genomeanalysis/bin/spades-core /Users/fionashavilof/Desktop/GAASR/spadesoutput/K21/configs/config.info
/Users/fionashavilof/miniconda3/envs/genomeanalysis/bin/spades-core /Users/fionashavilof/Desktop/GAASR/spadesoutput/K33/configs/config.info
/Users/fionashavilof/miniconda3/envs/genomeanalysis/bin/spades-core /Users/fionashavilof/Desktop/GAASR/spadesoutput/K55/configs/config.info
/Users/fionashavilof/miniconda3/envs/genomeanalysis/bin/spades-core /Users/fionashavilof/Desktop/GAASR/spadesoutput/K77/configs/config.info
/Users/fionashavilof/miniconda3/envs/genomeanalysis/bin/python3 /Users/fionashavilof/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/copy_files.py /Users/fionashavilof/Desktop/GAASR/spadesoutput/K77/before_rr.fasta /Users/fionashavilof/Desktop/GAASR/spadesoutput/before_rr.fasta /Users/fionashavilof/Desktop/GAASR/spadesoutput/K77/assembly_graph_after_simplification.gfa /Users/fionashavilof/Desktop/GAASR/spadesoutput/assembly_graph_after_simplification.gfa /Users/fionashavilof/Desktop/GAASR/spadesoutput/K77/final_contigs.fasta /Users/fionashavilof/Desktop/GAASR/spadesoutput/contigs.fasta /Users/fionashavilof/Desktop/GAASR/spadesoutput/K77/first_pe_contigs.fasta /Users/fionashavilof/Desktop/GAASR/spadesoutput/first_pe_contigs.fasta /Users/fionashavilof/Desktop/GAASR/spadesoutput/K77/strain_graph.gfa /Users/fionashavilof/Desktop/GAASR/spadesoutput/strain_graph.gfa /Users/fionashavilof/Desktop/GAASR/spadesoutput/K77/scaffolds.fasta /Users/fionashavilof/Desktop/GAASR/spadesoutput/scaffolds.fasta /Users/fionashavilof/Desktop/GAASR/spadesoutput/K77/scaffolds.paths /Users/fionashavilof/Desktop/GAASR/spadesoutput/scaffolds.paths /Users/fionashavilof/Desktop/GAASR/spadesoutput/K77/assembly_graph_with_scaffolds.gfa /Users/fionashavilof/Desktop/GAASR/spadesoutput/assembly_graph_with_scaffolds.gfa /Users/fionashavilof/Desktop/GAASR/spadesoutput/K77/assembly_graph.fastg /Users/fionashavilof/Desktop/GAASR/spadesoutput/assembly_graph.fastg /Users/fionashavilof/Desktop/GAASR/spadesoutput/K77/final_contigs.paths /Users/fionashavilof/Desktop/GAASR/spadesoutput/contigs.paths
true
/Users/fionashavilof/miniconda3/envs/genomeanalysis/bin/python3 /Users/fionashavilof/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /Users/fionashavilof/Desktop/GAASR/spadesoutput/scaffolds.fasta --misc_dir /Users/fionashavilof/Desktop/GAASR/spadesoutput/misc --threshold_for_breaking_scaffolds 3
true
